AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Function responsible for reading and processing a CSV file with user attributes from an S3 bucket and posting them to Braze API

Metadata:
  AWS::ServerlessRepo::Application:
    Name: braze-user-attribute-import
    Description: Processes user attribute CSV files and imports them to Braze
    Author: Braze
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README_APP_REPO.md
    Labels: ["braze", "user-attributes"]
    HomePageUrl: https://github.com/braze-inc/growth-shares-lambda-user-csv-import
    SemanticVersion: 0.1.2
    SourceCodeUrl: https://github.com/braze-inc/growth-shares-lambda-user-csv-import

Parameters:
  BrazeAPIKey:
    Type: String
    Description: Braze API Key necessary to authorize the connection
  BrazeAPIURL:
    Type: String
    Description: Braze API URL necessary to connect to Braze servers

Globals:
  Function:
    Timeout: 900

Resources:
  BrazeUserImportBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - "-"
        - - "braze-user-csv-import"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
    Metadata:
      Description: Uploading a CSV file to this bucket will trigger the User Attribute processing Lambda

  BrazeUserCSVImport:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: braze-user-csv-import
      CodeUri: braze_user_csv_import/
      Handler: app.lambda_handler
      Runtime: python3.6
      MemorySize: 2048
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Environment:
        Variables:
          BRAZE_API_KEY: !Ref BrazeAPIKey
          BRAZE_API_URL: !Ref BrazeAPIURL

      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref BrazeUserImportBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .csv
      Policies:
        - S3ReadPolicy:
            BucketName: !Join
              - "-"
              - - "braze-user-csv-import"
                - !Select
                  - 0
                  - !Split
                    - "-"
                    - !Select
                      - 2
                      - !Split
                        - "/"
                        - !Ref "AWS::StackId"
